### ISSUE TITLE
Kotlin 1.5.0-RC compatibility issue

### ISSUE THREAD

**Issue by sphrak** [ivanisidrowu/KtRssReader#69]
Hello, Kotlin 1.5.0-RC is around the corner and I checked if it played nicely with KtRssReader, but due to the new Duration api changes it wasn't happy about it;

```
java.lang.NoSuchMethodError: No static method getDays(I)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/~~8tbLKXsRF-XaLJOxrS_dhQ==/com.example.test.android.app-6jJoF5SXNmXOC7dOK8x6_g==/base.apk!classes26.dex)
        at tw.ktrssreader.config.KtRssReaderConfig.<init>(KtRssReaderConfig.kt:31)
        at com.example.test.android.feed.net.FeedNetDataSourceImpl.read(FeedNetDataSourceImpl.kt:19)
        at com.example.test.android.feed.FeedRepositoryImpl$fetchFeed$2.invokeSuspend(FeedRepositoryImpl.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I started here: https://github.com/ivanisidrowu/KtRssReader/pull/70 but I havent tried it yet since I couldn't figure out where you change the project version so I could publish locally and try it in my own project..

**edit:** I did some further investigation and its still unclear what causes this crash, only did the problem go away if I uninstalled the kotlin plugin in android studio (canary) and reinstalled the latest stable one via _File_ -> _Settings_ -> _Build, Execution, Deployment_ -> _Build Tools_ -> _Gradle_.

**Comment by sphrak** [comment]
Update: this seems to have been caused by a bug in the kotlin compiler plugin. Kotlin 1.5.0 was released today together with a new compiler plugin and I no longer get this issue. I'll close this issue, feel free to do whatever with the pull request #70

**Comment by ivanisidrowu** [comment]
@sphrak, thanks for the contribution!

**Comment by sphrak** [comment]
@ivanisidrowu I take it back, I was too quick yesterday -- the issue reported does not happen at compile time -- only in runtime so the issue is still there. I will fix the comments and also target the stable version instead of the release candidate
