### ISSUE TITLE
IllegalAccessError: cannot access class com.sun.org.apache.xerces.internal.dom.DeferredElementImpl

### ISSUE THREAD

**Issue by NorbertSandor** [ivanisidrowu/KtRssReader#82]
It seems that the implementation uses internal (non-exported) classes:

```
class tw.ktrssreader.kotlin.parser.ParserBase (in unnamed module @0x443effcb) cannot access class com.sun.org.apache.xerces.internal.dom.DeferredElementImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.dom to unnamed module @0x443effcb
java.lang.IllegalAccessError: class tw.ktrssreader.kotlin.parser.ParserBase (in unnamed module @0x443effcb) cannot access class com.sun.org.apache.xerces.internal.dom.DeferredElementImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.dom to unnamed module @0x443effcb
	at tw.ktrssreader.kotlin.parser.ParserBase.readString(ParserBase.kt:229)
	at tw.ktrssreader.kotlin.parser.AutoMixParser.parseChannelTags(AutoMixParser.kt:136)
	at tw.ktrssreader.kotlin.parser.AutoMixParser.parse(AutoMixParser.kt:89)
```

Environment: Java 17, Kotlin 1.7.20

**Comment by ivanisidrowu** [comment]
Thanks! Will check on that.
